import TopBar from "@/components/TopBar";
import { fetchData } from "@/lib/utils";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

const TemplateLayout = async ({ children }: { children: React.ReactNode }) => {
  const { data, error } = await fetchData(process.env.NEXT_PUBLIC_PHONE_NUMBER_ID);

  if (error) throw new Error(error);

  return (
    <section className="w-full">
      <TopBar data={data} />
      <main className="pt-11 h-full">{children}</main>
    </section>
  );
};

export default TemplateLayout;
