import TopBar from "@/components/TopBar";
import { fetchData } from "@/lib/utils";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

const DashboardLayout = async ({ children }: { children: React.ReactNode }) => {
  const data = await fetchData();

  return (
    <section className="w-full">
      <TopBar data={data?.data} />
      <main className="pt-11 h-full">{children}</main>
    </section>
  );
};

export default DashboardLayout;
