import TopBar from "@/components/TopBar";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

const DashboardLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <section className="w-full">
      <TopBar />
      <main className="pt-11 h-full">{children}</main>
    </section>
  );
};

export default DashboardLayout;
